name: flutter_fbx3d_viewer
description: Flutter package for viewing Fbx 3d animated files with textures, basic lights, colors.
version: 1.0.0
homepage: https://github.com/klaszlo8207/Flutter-FBX-3D-Viewer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  vector_math: ^2.0.8
  provider: ^4.0.2
  archive: '>= 2.0.0 <3.0.0'
  image: '>= 2.0.0 <3.0.0'

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
    #assets:
    #- assets/knight.fbx

